services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: iconstruye-backend
    container_name: backend-iconstruye
    env_file:
      - ./server/.env
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
    networks:
      - app_network
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: iconstruye-frontend
    container_name: frontend-iconstruye
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
